# Generated by Django 2.2 on 2019-04-15 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blogto_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='is_multiple_days',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event_loop.Location'),
        ),
    ]
