# Generated by Django 2.2 on 2019-04-15 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0003_auto_20190415_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
