# Generated by Django 2.2 on 2019-04-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0004_auto_20190415_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event_loop.Location'),
            preserve_default=False,
        ),
    ]
