# Generated by Django 2.2 on 2019-04-15 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0005_auto_20190415_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='blogto_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event_loop.Location'),
        ),
    ]
