# Generated by Django 2.2 on 2019-04-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0006_auto_20190415_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='blogto_id',
            field=models.IntegerField(),
        ),
    ]
