# Generated by Django 2.2 on 2019-04-16 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0007_auto_20190415_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
