# Generated by Django 2.2 on 2019-04-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0008_auto_20190416_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
