# Generated by Django 2.2 on 2019-04-16 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0010_auto_20190416_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
