# Generated by Django 2.2 on 2019-04-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0011_auto_20190416_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
    ]
