# Generated by Django 2.2 on 2019-04-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0012_auto_20190416_1932'),
        ('event_loop', '0009_auto_20190416_2120'),
    ]

    operations = [
    ]
