# Generated by Django 2.2 on 2019-04-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0012_auto_20190416_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(default='venue name goes here', max_length=255),
            preserve_default=False,
        ),
    ]
