# Generated by Django 2.2 on 2019-04-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0013_auto_20190417_1743'),
        ('event_loop', '0013_merge_20190417_1548'),
    ]

    operations = [
    ]
