# Generated by Django 2.2 on 2019-04-23 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0016_auto_20190423_2139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('latitude', 'longitude')},
        ),
    ]
