# Generated by Django 2.2 on 2019-04-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_loop', '0018_auto_20190424_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
